# Generated by Django 5.1.7 on 2026-05-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0003_annualprocurementplan_approval_trail_and_more'),
        ('requisitions', '0002_alter_requisition_delivery_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='app_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='procurement_planning.applineitem'),
        ),
    ]
