# Generated by Django 5.1.7 on 2026-05-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_requisition_app_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_dept_head', 'Pending Department Head Approval'), ('pending_finance', 'Pending Finance Validation'), ('pending_dg', 'Pending Director General Approval'), ('pending_zpc', 'Pending ZPC Approval'), ('approved', 'Approved for Procurement'), ('rejected', 'Rejected'), ('amended', 'Amended')], default='draft', max_length=50),
        ),
    ]
