# Generated by Django 5.0.6 on 2026-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_alter_requisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisitionitem',
            name='attachment',
            field=models.TextField(blank=True, help_text='Supporting document for this line item (spec sheet, quote, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='technical_review_required',
            field=models.BooleanField(default=False, help_text='Auto-set when any goods line item exceeds K1,000,000'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='attachment',
            field=models.FileField(blank=True, help_text='Supporting document for this line item (spec sheet, quote, etc.)', null=True, upload_to='requisition_attachments/'),
        ),
    ]
