# Generated by Django 5.0.6 on 2026-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0005_historicalrequisitionitem_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_dept_head', 'Pending Department Head Approval'), ('pending_finance', 'Pending Finance Validation'), ('pending_dg', 'Pending Director General Approval'), ('pending_zpc', 'Pending ZPC Approval'), ('approved', 'Approved for Procurement'), ('rejected', 'Rejected'), ('amended', 'Amended'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
