# Generated by Django 5.0.6 on 2026-06-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_closurechecklist_extended_fields'),
        ('procurement_planning', '0011_alter_procurementmilestone_variance_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractmilestone',
            options={'ordering': ['sequence_number', 'planned_date'], 'verbose_name': 'Contract Milestone', 'verbose_name_plural': 'Contract Milestones'},
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='source_procurement_milestone',
            field=models.ForeignKey(blank=True, help_text='Reference to the CPP里程碑 this contract milestone was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_milestones', to='procurement_planning.procurementmilestone'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='variance_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='variance_flag',
            field=models.CharField(blank=True, choices=[('green', 'On Time / Early'), ('yellow', '1-7 Days Late'), ('orange', '8-14 Days Late'), ('red', '>14 Days Late / Critical')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractmilestone',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractmilestone',
            name='milestone_name',
            field=models.CharField(default='Milestone', max_length=255),
        ),
    ]
