# Generated by Codex on 2026-06-08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contractmilestone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amendment_cap_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2500'), max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='archive_after_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='archive_retention_years',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='contract',
            name='liquidated_damages_cap_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='liquidated_damages_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0050'), max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='retention_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5),
        ),
        migrations.AddField(
            model_name='closurechecklist',
            name='all_invoices_submitted_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquidateddamages',
            name='cap_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidateddamages',
            name='weekly_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0050'), max_digits=8),
        ),
        migrations.AddField(
            model_name='liquidateddamages',
            name='weeks_late',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
