# Generated by Django 5.0.6 on 2026-06-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_bidevaluationreport_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictofinterest',
            name='confidentiality_agreed',
            field=models.BooleanField(default=False, help_text='Member agreed to maintain confidentiality'),
        ),
        migrations.AddField(
            model_name='conflictofinterest',
            name='conflicted_bidders',
            field=models.JSONField(blank=True, default=list, help_text='List of bidder IDs or names for specific conflicts'),
        ),
        migrations.AddField(
            model_name='conflictofinterest',
            name='declaration_type',
            field=models.CharField(choices=[('no_conflict', 'No Conflict'), ('general_conflict', 'General Conflict'), ('specific_conflict', 'Conflict with Specific Bidder(s)')], default='no_conflict', max_length=30),
        ),
        migrations.AddField(
            model_name='conflictofinterest',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Explanation required when conflict is declared'),
        ),
    ]
