# Generated by Django 5.0.6 on 2026-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_conflictofinterest_confidentiality_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcommittee',
            name='require_coi',
            field=models.BooleanField(default=True, help_text='Require COI declarations from all members before evaluation'),
        ),
    ]
