# Generated by Django 5.0.6 on 2026-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_add_committee_require_coi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidevaluationreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
