# Generated by Django 5.1.7 on 2026-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_bidevaluationreport_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidevaluationreport',
            name='ber_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
