# Generated by Django 5.0.6 on 2026-07-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_enhance_post_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcommittee',
            name='non_official_members',
            field=models.JSONField(blank=True, default=list, help_text='List of {first_name, last_name, email, expertise} for external/non-official members'),
        ),
        migrations.AlterField(
            model_name='evaluationcommittee',
            name='members',
            field=models.JSONField(default=list, help_text='List of user IDs for official committee members'),
        ),
    ]
