# Generated by Django 5.0.6 on 2026-07-21 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_bidopening_location'),
        ('evaluations', '0012_evaluationcommittee_non_official_members_and_more'),
        ('solicitations', '0015_alter_solicitationtemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcommittee',
            name='non_official_members',
            field=models.JSONField(blank=True, default=list, help_text='List of {first_name, last_name, email, expertise, valid_from, valid_until} for external/non-official members'),
        ),
        migrations.CreateModel(
            name='AwardAppeal',
            fields=[
                ('appeal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('upheld', 'Upheld (Award Overturned)'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], default='filed', max_length=20)),
                ('grounds', models.CharField(choices=[('scoring_error', 'Scoring or Evaluation Error'), ('procedural', 'Procedural Irregularity'), ('conflict_of_interest', 'Conflict of Interest'), ('eligibility', 'Eligibility / Qualification Error'), ('specification', 'Specification Deviation'), ('bias', 'Bias or Discrimination'), ('other', 'Other')], max_length=30)),
                ('grounds_detail', models.TextField(blank=True, default='', help_text='Detailed description of the grounds for appeal')),
                ('supporting_documents', models.JSONField(blank=True, default=list, help_text='List of {name, description, file_url} for supporting evidence')),
                ('resolution', models.TextField(blank=True, default='', help_text='Resolution outcome and reasoning')),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_deadline', models.DateTimeField(blank=True, help_text='Deadline for resolving the appeal (typically 14 days from filing)', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='bids.bidsubmission')),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_appeals', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_appeals', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_appeals', to='solicitations.solicitation')),
            ],
            options={
                'verbose_name': 'Award Appeal',
                'verbose_name_plural': 'Award Appeals',
                'db_table': 'eval_award_appeal',
            },
        ),
    ]
