# Generated by Django 5.0.6 on 2026-07-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_award_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardappeal',
            name='clarification_request',
            field=models.TextField(blank=True, default='', help_text='Clarification question sent to the bidder'),
        ),
        migrations.AddField(
            model_name='awardappeal',
            name='clarification_requested',
            field=models.BooleanField(default=False, help_text='Whether a clarification has been requested from the bidder'),
        ),
        migrations.AddField(
            model_name='awardappeal',
            name='clarification_response',
            field=models.TextField(blank=True, default='', help_text='Bidder response to the clarification request'),
        ),
        migrations.AddField(
            model_name='awardappeal',
            name='decision_letter_url',
            field=models.CharField(blank=True, default='', help_text='URL of the uploaded appeal decision letter', max_length=500),
        ),
        migrations.AddField(
            model_name='awardappeal',
            name='hearing_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled hearing or meeting date for reviewing the appeal', null=True),
        ),
        migrations.AddField(
            model_name='awardappeal',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Internal procurement officer review notes (not visible to bidder)'),
        ),
    ]
