# Generated by Django 5.0.6 on 2026-07-23 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_awardappeal_clarification_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealActionLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('filed', 'Appeal Filed'), ('acknowledged', 'Appeal Acknowledged'), ('under_review', 'Taken Under Review'), ('review_notes_added', 'Review Notes Added'), ('hearing_scheduled', 'Hearing Scheduled'), ('clarification_requested', 'Clarification Requested'), ('clarification_received', 'Clarification Response Received'), ('upheld', 'Appeal Upheld'), ('dismissed', 'Appeal Dismissed'), ('withdrawn', 'Appeal Withdrawn')], max_length=30)),
                ('details', models.TextField(blank=True, default='', help_text='Additional details about the action taken')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured data about the action (e.g. old_status, new_status)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='evaluations.awardappeal')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appeal Action Log',
                'verbose_name_plural': 'Appeal Action Logs',
                'db_table': 'eval_appeal_action_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
