# Generated by Django 5.0.6 on 2026-07-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_appealactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardappeal',
            name='decision_letter_url',
        ),
        migrations.AddField(
            model_name='awardappeal',
            name='decision_letter',
            field=models.FileField(blank=True, default='', help_text='Uploaded appeal decision letter PDF', upload_to='appeals/decision_letters/'),
        ),
    ]
