# Generated by Django 5.0.6 on 2026-07-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0016_remove_awardappeal_decision_letter_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealactionlog',
            name='action',
            field=models.CharField(choices=[('filed', 'Appeal Filed'), ('acknowledged', 'Appeal Acknowledged'), ('under_review', 'Taken Under Review'), ('review_notes_added', 'Review Notes Added'), ('hearing_scheduled', 'Hearing Scheduled'), ('clarification_requested', 'Clarification Requested'), ('clarification_received', 'Clarification Response Received'), ('upheld', 'Appeal Upheld'), ('dismissed', 'Appeal Dismissed'), ('withdrawn', 'Appeal Withdrawn'), ('re_evaluation_initiated', 'Re-Evaluation Initiated')], max_length=30),
        ),
    ]
