# Generated by Django 5.1.7 on 2026-07-26 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0018_add_evaluated_by_to_preliminaryexam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedscore',
            name='consolidated_at',
            field=models.DateTimeField(blank=True, help_text='When the scores were consolidated by the chairperson', null=True),
        ),
        migrations.AddField(
            model_name='combinedscore',
            name='consolidated_by',
            field=models.ForeignKey(blank=True, help_text='Chairperson who consolidated the scores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidated_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
