# Generated by Django 5.0.6 on 2026-07-26 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0019_combinedscore_consolidated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postqualification',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='SLA deadline for completing post-qualification verification', null=True),
        ),
        migrations.AlterField(
            model_name='financialevaluation',
            name='preference_category',
            field=models.CharField(choices=[('non_citizen', 'Non-Citizen'), ('citizen_owned', 'Citizen-Owned'), ('citizen_empowered', 'Citizen-Empowered'), ('citizen_influenced', 'Citizen-Influenced')], default='non_citizen', max_length=20),
        ),
        migrations.CreateModel(
            name='PQActionLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('item_updated', 'Verification Item Updated'), ('checklist_generated', 'Checklist Generated'), ('pq_assigned', 'Post-Qualification Assigned'), ('pq_reassigned', 'Post-Qualification Reassigned'), ('pq_cleared', 'Post-Qualification Cleared'), ('pq_failed', 'Post-Qualification Failed'), ('notes_added', 'Overall Notes Added')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured data about the action (e.g. item_id, old_status, new_status)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pq_actions', to=settings.AUTH_USER_MODEL)),
                ('pq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='evaluations.postqualification')),
            ],
            options={
                'verbose_name': 'PQ Action Log',
                'verbose_name_plural': 'PQ Action Logs',
                'db_table': 'eval_pq_action_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
