# Generated by Django 5.0.6 on 2026-07-27 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_bidopening_location'),
        ('evaluations', '0020_postqualification_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postqualification',
            index=models.Index(fields=['status'], name='idx_pq_status'),
        ),
        migrations.AddIndex(
            model_name='postqualification',
            index=models.Index(fields=['deadline'], name='idx_pq_deadline'),
        ),
        migrations.AddIndex(
            model_name='postqualification',
            index=models.Index(fields=['assigned_to'], name='idx_pq_assigned_to'),
        ),
        migrations.AddIndex(
            model_name='postqualification',
            index=models.Index(fields=['created_at'], name='idx_pq_created_at'),
        ),
        migrations.AddIndex(
            model_name='pqactionlog',
            index=models.Index(fields=['pq', 'created_at'], name='idx_pqlog_pq_created'),
        ),
        migrations.AddIndex(
            model_name='pqactionlog',
            index=models.Index(fields=['action'], name='idx_pqlog_action'),
        ),
    ]
