# Generated by Django 5.0.6 on 2026-07-28 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_pq_upgrade_post_qualification'),
        ('evaluations', '0021_add_pq_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postqualification',
            name='chair_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='chair_decision',
            field=models.CharField(blank=True, choices=[('', 'Pending'), ('passed', 'Post-Qualification Passed'), ('failed', 'Post-Qualification Failed')], default='', help_text='Chair overall decision after reviewing all checks', max_length=20),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='chair_decision_notes',
            field=models.TextField(blank=True, default='', help_text='Chair narrative explaining the overall assessment'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='rank',
            field=models.IntegerField(blank=True, help_text='Rank from CombinedScore at time of PQ creation', null=True),
        ),
        migrations.AlterField(
            model_name='postqualification',
            name='verification_items',
            field=models.JSONField(blank=True, default=list, help_text='List of {id, label, category, status, notes, verified_by, verified_at, verification_method, auto_data}'),
        ),
        migrations.AlterField(
            model_name='pqactionlog',
            name='action',
            field=models.CharField(choices=[('item_updated', 'Verification Item Updated'), ('checklist_generated', 'Checklist Generated'), ('pq_assigned', 'Post-Qualification Assigned'), ('pq_reassigned', 'Post-Qualification Reassigned'), ('pq_cleared', 'Post-Qualification Cleared'), ('pq_failed', 'Post-Qualification Failed'), ('notes_added', 'Overall Notes Added'), ('chair_decision', 'Chair Decision Recorded'), ('auto_verified', 'Auto-Verification Completed'), ('reference_contacted', 'Reference Contacted')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='postqualification',
            index=models.Index(fields=['rank'], name='idx_pq_rank'),
        ),
    ]
