# Generated by Django 5.0.6 on 2026-07-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_pq_upgrade_post_qualification'),
        ('evaluations', '0022_pq_upgrade_post_qualification'),
        ('solicitations', '0015_alter_solicitationtemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postqualification',
            name='committee_review',
            field=models.JSONField(blank=True, default=list, help_text='List of {member_id, member_name, decision, comments, decided_at} for committee review'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of conditions when result is award_with_conditions: {condition, deadline, status, verified_at}'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='initiation_date',
            field=models.DateTimeField(blank=True, help_text='When the PQ process was formally initiated', null=True),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='pq_document_requests',
            field=models.JSONField(blank=True, default=list, help_text='List of {request_id, document_type, description, requested_at, requested_by, due_date, submitted_at, file_url, status}'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='recommendation',
            field=models.TextField(blank=True, default='', help_text='PQ Officer recommendation to the committee'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='recommended_by',
            field=models.ForeignKey(blank=True, help_text='PQ Officer who made the recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pq_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='result',
            field=models.CharField(blank=True, choices=[('', 'Not Decided'), ('award', 'Award — All Checks Passed'), ('award_with_conditions', 'Award with Conditions'), ('no_award', 'No Award — Failed')], default='', help_text='Final PQ result after committee decision', max_length=30),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='solicitation',
            field=models.ForeignKey(blank=True, help_text='Direct reference to the solicitation (denormalized for ease of querying)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_qualifications', to='solicitations.solicitation'),
        ),
        migrations.AddField(
            model_name='postqualification',
            name='workflow_stage',
            field=models.CharField(blank=True, choices=[('initiation', 'Initiation'), ('desktop_review', 'Desktop Review'), ('document_collection', 'Document Collection'), ('site_inspection', 'Site Inspection'), ('reference_check', 'Reference Check'), ('evaluation', 'Evaluation & Recommendation'), ('committee_review', 'Committee Review'), ('closed', 'Closed')], default='initiation', help_text='Current active workflow stage', max_length=30),
        ),
        migrations.AlterField(
            model_name='postqualification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiation', 'Initiation'), ('desktop_review', 'Desktop Review'), ('document_collection', 'Document Collection'), ('site_inspection', 'Site Inspection'), ('reference_check', 'Reference Check'), ('evaluation', 'Evaluation'), ('committee_review', 'Committee Review'), ('cleared', 'Cleared'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pqactionlog',
            name='action',
            field=models.CharField(choices=[('item_updated', 'Verification Item Updated'), ('checklist_generated', 'Checklist Generated'), ('pq_assigned', 'Post-Qualification Assigned'), ('pq_reassigned', 'Post-Qualification Reassigned'), ('pq_cleared', 'Post-Qualification Cleared'), ('pq_failed', 'Post-Qualification Failed'), ('notes_added', 'Overall Notes Added'), ('chair_decision', 'Chair Decision Recorded'), ('auto_verified', 'Auto-Verification Completed'), ('reference_contacted', 'Reference Contacted'), ('stage_changed', 'Workflow Stage Changed'), ('document_requested', 'Document Requested'), ('document_submitted', 'Document Submitted'), ('condition_added', 'Condition Added'), ('condition_verified', 'Condition Verified'), ('recommendation_submitted', 'Recommendation Submitted'), ('committee_reviewed', 'Committee Member Reviewed'), ('pq_initiated', 'Post-Qualification Initiated')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='postqualification',
            index=models.Index(fields=['workflow_stage'], name='idx_pq_workflow_stage'),
        ),
        migrations.AddIndex(
            model_name='postqualification',
            index=models.Index(fields=['solicitation', 'status'], name='idx_pq_sol_stat'),
        ),
    ]
