# Generated by Django 5.1.7 on 2026-05-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method_selection', '0002_initial'),
        ('requisitions', '0004_alter_requisition_status'),
        ('solicitations', '0006_solicitation_egp_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonopenjustification',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_justifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonopenjustification',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonopenjustification',
            name='solicitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_open_justifications', to='solicitations.solicitation'),
        ),
        migrations.AddField(
            model_name='nonopenjustification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonopenjustification',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_justifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonopenjustification',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_open_justifications', to='requisitions.requisition'),
        ),
    ]
