# Generated by Django 5.0.6 on 2026-06-08 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_closurechecklist_extended_fields'),
        ('finance', '0005_goodsreceiptnote_nullable_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='retained_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retention withheld (5-10% per BR-FIN-02)', max_digits=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='retention_released',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GRNLineItem',
            fields=[
                ('line_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.goodsreceiptnote')),
            ],
            options={
                'verbose_name': 'GRN Line Item',
                'verbose_name_plural': 'GRN Line Items',
                'db_table': 'fin_grn_line_item',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('line_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'fin_invoice_line_item',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRelease',
            fields=[
                ('release_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_certificate_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_releases', to='contracts.contract')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retention Release',
                'verbose_name_plural': 'Retention Releases',
                'db_table': 'fin_retention_release',
                'ordering': ['-released_at'],
            },
        ),
    ]
