# Generated by Django 5.0.6 on 2026-06-08 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_closurechecklist_extended_fields'),
        ('suppliers', '0001_initial'),
        ('finance', '0006_payment_retained_amount_payment_retention_released_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAdvice',
            fields=[
                ('advice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advice_number', models.CharField(max_length=100, unique=True)),
                ('item_description', models.TextField(blank=True, default='')),
                ('quantity_advised', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('source', models.CharField(default='supplier_portal', max_length=50)),
                ('submitted_by', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, default='', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, default='', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_advices', to='contracts.contract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_advices', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Delivery Advice',
                'verbose_name_plural': 'Delivery Advices',
                'db_table': 'fin_delivery_advice',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='delivery_advice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_grns', to='finance.deliveryadvice'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='verified_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='verification_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
