# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_payment_reconciliation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='cold_chain_maintained',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('rejected', 'Rejected')], default='complete', max_length=20),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='temperature_log_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='zamra_certificate_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('rejected', 'Rejected')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='liquidated_damages_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_before_retention',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='undelivered_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_matching', 'Pending 3-Way Match'), ('finance_reviewed', 'Finance Reviewed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved for Payment'), ('fully_approved', 'Fully Approved'), ('paid', 'Paid'), ('payment_failed', 'Payment Failed'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
