# Generated by Django 5.1.7 on 2026-06-08 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_execution_rules_and_closure_invoice_gate'),
        ('finance', '0009_execution_grn_invoice_finance_review_fields'),
        ('suppliers', '0002_vendor_application_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='contracts.contract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'fin_purchase_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('line_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Line Item',
                'verbose_name_plural': 'PO Line Items',
                'db_table': 'fin_po_line_item',
                'ordering': ['line_number'],
            },
        ),
    ]
