# Generated by Django 5.0.6 on 2026-06-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_purchaseorder_purchaseorderlineitem'),
    ]

    operations = []
