# Generated by Django 5.1.7 on 2026-06-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_grnlineitem_po_line_item_invoice_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='temperature_log',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zamra_certificate',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
