# Generated by Django 5.1.7 on 2026-06-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_grnlineitem_po_line_item_invoice_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnlineitem',
            name='po_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_line_items', to='finance.purchaseorderlineitem'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='grn_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line_items', to='finance.grnlineitem'),
        ),
    ]
