export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    TENDERS: '/tenders',
    SUPPLIERS: '/suppliers',
    ABOUT: '/about',
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
  VENDOR: {
    DASHBOARD: '/vendor/dashboard',
    BIDS: '/vendor/bids',
    BID_DETAIL: '/vendor/bids/:id',
    SOLICITATIONS: '/vendor/solicitations',
    SOLICITATION_DETAIL: '/vendor/solicitations/:id',
    CONTRACTS: '/vendor/contracts',
    CONTRACT_DETAIL: '/vendor/contracts/:id',
    PROFILE: '/vendor/profile',
  },
  DASHBOARD: {
    HOME: '/dashboard',
    REQUISITIONS: '/requisitions',
    REQUISITION_DETAIL: '/requisitions/:id',
    REQUISITION_CREATE: '/requisitions/create',
    REQUISITION_EDIT: '/requisitions/:id/edit',
    SOLICITATIONS: '/solicitations',
    SOLICITATION_DETAIL: '/solicitations/:id',
    SOLICITATION_CREATE: '/solicitations/create',
    BIDS: '/bids',
    BID_DETAIL: '/bids/:id',
    EVALUATIONS: '/evaluations',
    EVALUATION_DETAIL: '/evaluations/:id',
    CONTRACTS: '/contracts',
    CONTRACT_DETAIL: '/contracts/:id',
    CONTRACT_CREATE: '/contracts/create',
    FINANCE: '/finance',
    FINANCE_BUDGETS: '/finance/budgets',
    FINANCE_INVOICES: '/finance/invoices',
    FINANCE_PAYMENTS: '/finance/payments',
    FINANCE_LC: '/finance/letters-of-credit',
    SUPPLIERS: '/suppliers',
    SUPPLIER_DETAIL: '/suppliers/:id',
    REPORTS: '/reports',
    CHANGE_PASSWORD: '/change-password',
  },
  ADMIN: {
    HOME: '/admin',
    USERS: '/admin/users',
    USER_CREATE: '/admin/users/create',
    USER_EDIT: '/admin/users/:id/edit',
    SETTINGS: '/admin/settings',
    AUDIT: '/admin/audit',
    APPROVALS: '/admin/approvals',
    DEPARTMENTS: '/admin/departments',
    PROCUREMENT_METHODS: '/admin/procurement-methods',
    NOTIFICATIONS: '/admin/notifications',
  },
  SUPPLIER_RELATIONS: {
    HOME: '/supplier-relations',
    DASHBOARD: '/supplier-relations',
    VENDOR_APPLICATIONS: '/supplier-relations/vendor-applications',
    VENDORS: '/supplier-relations/vendors',
    REPORTS: '/supplier-relations/reports',
  },
} as const;
