# Generated by Django 5.1.7 on 2026-06-18 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdSequence',
            fields=[
                ('sequence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=4)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('department_code', models.CharField(max_length=3)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ID Sequence',
                'verbose_name_plural': 'ID Sequences',
                'db_table': 'master_id_sequence',
                'ordering': ['prefix', 'fiscal_year', 'department_code'],
                'unique_together': {('prefix', 'fiscal_year', 'department_code')},
            },
        ),
    ]
