from django.urls import path
from . import views

urlpatterns = [
    path('annual-plans/', views.AnnualProcurementPlanListView.as_view(), name='app-list'),
    path('annual-plans/dashboard/', views.app_dashboard_view, name='app-dashboard'),
    path('annual-plans/<uuid:pk>/', views.AnnualProcurementPlanDetailView.as_view(), name='app-detail'),
    path('annual-plans/<uuid:pk>/submit/', views.app_submit_view, name='app-submit'),
    path('annual-plans/<uuid:pk>/bulk-line-items/', views.app_bulk_line_items_view, name='app-bulk-line-items'),
    path('annual-plans/<uuid:pk>/approve/', views.app_approve_view, name='app-approve'),
    path('annual-plans/<uuid:pk>/reject/', views.app_reject_view, name='app-reject'),
    path('annual-plans/<uuid:pk>/return/', views.app_return_view, name='app-return'),
    path('annual-plans/<uuid:pk>/publish/', views.app_publish_view, name='app-publish'),
    path('annual-plans/<uuid:pk>/compliance/', views.app_compliance_check_view, name='app-compliance'),
    path('annual-plans/<uuid:pk>/consolidate/', views.app_consolidate_view, name='app-consolidate'),
    path('annual-plans/<uuid:pk>/approval-trail/', views.app_approval_trail_view, name='app-approval-trail'),
    path('annual-plans/<uuid:pk>/generate-gpn/', views.gpn_generate_view, name='app-generate-gpn'),
    path('annual-plans/<uuid:pk>/zppa-submit/', views.app_zppa_submit_view, name='app-zppa-submit'),
    path('annual-plans/zppa-deadline-alerts/', views.app_zppa_deadline_alerts_view, name='app-zppa-deadline-alerts'),
    path('line-items/', views.APPLineItemListView.as_view(), name='line-items'),
    path('line-items/<uuid:pk>/', views.APPLineItemDetailView.as_view(), name='app-line-item-detail'),
    path('contract-plans/', views.ContractProcurementPlanListView.as_view(), name='cpp-list'),
    path('contract-plans/<uuid:pk>/', views.ContractProcurementPlanDetailView.as_view(), name='cpp-detail'),
    path('contract-plans/<uuid:pk>/submit/', views.cpp_submit_view, name='cpp-submit'),
    path('contract-plans/<uuid:pk>/approve/', views.cpp_approve_view, name='cpp-approve'),
    path('contract-plans/<uuid:pk>/reject/', views.cpp_reject_view, name='cpp-reject'),
    path('contract-plans/<uuid:pk>/return/', views.cpp_return_view, name='cpp-return'),
    path('contract-plans/<uuid:pk>/method-override-approve/', views.cpp_method_override_approve_view, name='cpp-method-override-approve'),
    path('contract-plans/<uuid:pk>/lock-baseline/', views.cpp_lock_baseline_view, name='cpp-lock-baseline'),
    path('contract-plans/<uuid:pk>/update-milestone/<uuid:milestone_pk>/', views.cpp_update_milestone_view, name='cpp-update-milestone'),
    path('contract-plans/<uuid:pk>/create-amendment/', views.cpp_create_amendment_view, name='cpp-create-amendment'),
    path('contract-plans/dashboard/', views.cpp_dashboard_view, name='cpp-dashboard'),
    path('contract-plans/variance-alerts/', views.cpp_variance_alerts_view, name='cpp-variance-alerts'),
    path('contract-plans/<uuid:pk>/archive/', views.cpp_archive_view, name='cpp-archive'),
    path('milestones/', views.ProcurementMilestoneListView.as_view(), name='milestone-list'),
    path('milestones/<uuid:pk>/', views.ProcurementMilestoneDetailView.as_view(), name='milestone-detail'),
    path('notices/', views.GeneralProcurementNoticeListView.as_view(), name='gpn-list'),
    path('notices/<uuid:pk>/', views.GeneralProcurementNoticeDetailView.as_view(), name='gpn-detail'),
    path('notices/<uuid:pk>/publish/', views.gpn_publish_view, name='gpn-publish'),
    path('notices/<uuid:pk>/archive/', views.gpn_archive_view, name='gpn-archive'),
    path('public/gpns/', views.public_gpn_list_view, name='public-gpn-list'),
    path('public/gpns/<uuid:pk>/', views.public_gpn_detail_view, name='public-gpn-detail'),
]
