from django.urls import path
from . import views

app_name = 'evaluations'

urlpatterns = [
    path('committees/', views.EvaluationCommitteeListView.as_view(), name='committee-list'),
    path('committees/<uuid:pk>/', views.EvaluationCommitteeDetailView.as_view(), name='committee-detail'),
    path('committees/<uuid:committee_pk>/declare-coi/', views.coi_declare_view, name='coi-declare'),
    path('committees/<uuid:committee_pk>/coi/', views.coi_committee_view, name='coi-committee'),
    path('preliminary/', views.PreliminaryExamListView.as_view(), name='preliminary-list'),
    path('preliminary/<uuid:pk>/', views.PreliminaryExamDetailView.as_view(), name='preliminary-detail'),
    path('technical-scores/', views.TechnicalScoreListView.as_view(), name='technical-score-list'),
    path('technical-scores/<uuid:pk>/', views.TechnicalScoreDetailView.as_view(), name='technical-score-detail'),
    path('technical-scores/submit/', views.technical_score_submit_view, name='technical-score-submit'),
    path('technical-scores/my/<uuid:bid_pk>/', views.technical_scores_my_view, name='technical-scores-my'),
    path('technical-scores/averages/<uuid:bid_pk>/', views.technical_score_calculate_averages_view, name='technical-score-averages'),
    path('technical-scores/threshold-check/<uuid:bid_pk>/', views.technical_score_threshold_check_view, name='technical-score-threshold'),
    path('financial/calculate/<uuid:bid_pk>/', views.financial_evaluation_calculate_view, name='financial-calculate'),
    path('financial/authorize-open/<uuid:solicitation_pk>/', views.authorize_financial_opening_view, name='authorize-financial-open'),
    path('financial/passed-bids/<uuid:solicitation_pk>/', views.list_passed_tech_bids_view, name='financial-passed-bids'),
    path('consolidation/<uuid:solicitation_pk>/', views.consolidated_scores_view, name='consolidated-scores'),
    path('combined-scores/', views.CombinedScoreListView.as_view(), name='combined-score-list'),
    path('qcbs/<uuid:solicitation_pk>/', views.calculate_qcbs_view, name='qcbs-calculate'),
    path('award/<uuid:solicitation_pk>/', views.select_winner_view, name='select-winner'),
    path('reports/', views.BidEvaluationReportListView.as_view(), name='ber-list'),
    path('reports/<uuid:pk>/', views.BidEvaluationReportDetailView.as_view(), name='ber-detail'),
    path('reports/generate/<uuid:solicitation_pk>/', views.ber_generate_view, name='ber-generate'),
    path('reports/<uuid:pk>/sign/', views.ber_sign_view, name='ber-sign'),
    path('reports/<uuid:pk>/signatures/', views.ber_committee_status_view, name='ber-signatures'),
    path('reports/<uuid:pk>/submit/', views.ber_submit_view, name='ber-submit'),
    path('reports/<uuid:pk>/approve/', views.ber_approve_view, name='ber-approve'),
    path('reports/<uuid:pk>/reject/', views.ber_reject_view, name='ber-reject'),
    path('reports/<uuid:pk>/pdf/', views.ber_pdf_view, name='ber-pdf'),
    path('post-qualifications/', views.PostQualificationListView.as_view(), name='pq-list'),
    path('post-qualifications/<uuid:pk>/', views.PostQualificationDetailView.as_view(), name='pq-detail'),
    path('post-qualifications/<uuid:pq_pk>/update-item/', views.pq_update_verification_item_view, name='pq-update-item'),
    path('post-qualifications/<uuid:pq_pk>/generate-checklist/', views.pq_generate_checklist_view, name='pq-generate-checklist'),
    path('post-qualifications/<uuid:pq_pk>/verification-context/', views.pq_verification_context_view, name='pq-verification-context'),
    path('phase-status/<uuid:solicitation_pk>/', views.evaluation_phase_status_view, name='phase-status'),
    path('award-appeals/', views.AwardAppealListView.as_view(), name='appeal-list'),
    path('award-appeals/<uuid:appeal_pk>/', views.AwardAppealDetailView.as_view(), name='appeal-detail'),
]
