# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_required', max_length=20),
        ),
    ]
