# Generated by Codex on 2026-06-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_notification_delivery_channels_and_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='config_noti_recipie_7aabdc_idx',
            old_name='config_noti_recipie_d6bb57_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='config_noti_notific_58474d_idx',
            old_name='config_noti_notific_68b2d0_idx',
        ),
    ]
