# Generated by Django 5.0.6 on 2026-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_bidopening_live_fields_and_opening_detail_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsubmission',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
