# Generated by Django 5.0.6 on 2026-06-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_add_bid_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidopening',
            name='location',
            field=models.CharField(blank=True, default='ZAMMSA Boardroom, Lusaka / Virtual', max_length=255),
        ),
    ]
