# Generated by Django 5.0.6 on 2026-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_bidopening_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddocument',
            name='document_type',
            field=models.CharField(choices=[('technical_proposal', 'Technical Proposal'), ('financial_proposal', 'Financial Proposal'), ('bid_security', 'Bid Security'), ('pacra_registration', 'PACRA Registration Certificate'), ('tax_clearance', 'Tax Clearance Certificate'), ('zamra_registration', 'ZAMRA Product Registration'), ('financial_statements', 'Audited Financial Statements'), ('bank_reference', 'Bank Reference Letter'), ('statutory_declaration', 'Statutory Declaration (Litigation/Insolvency)'), ('site_visit_report', 'Site Visit Report'), ('reference_letter', 'Reference Letter'), ('other', 'Other')], max_length=50),
        ),
    ]
