# Generated by Django 5.0.6 on 2026-07-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0009_pq_upgrade_post_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocument',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='biddocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biddocument',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='joint_venture_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='joint_venture_partners',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='late_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='lot_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='modification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='modification_reason',
            field=models.CharField(blank=True, choices=[('pricing_correction', 'Pricing Correction'), ('document_replacement', 'Document Replacement'), ('addenda_response', 'Addenda Response'), ('clarification', 'Clarification'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='parent_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='bids.bidsubmission'),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='submitted_from_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bidsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('opened', 'Opened'), ('responsive', 'Responsive'), ('non_responsive', 'Non-Responsive'), ('withdrawn', 'Withdrawn'), ('modified', 'Modified'), ('awarded', 'Awarded')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='bidsubmission',
            name='submission_method',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=20),
        ),
    ]
