# Generated by Django 5.1.7 on 2026-05-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0003_annualprocurementplan_approval_trail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualprocurementplan',
            name='gpn_publication_proofs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='gpn_publication_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='gpn_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='zppa_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='zppa_deadline_alerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='zppa_submission_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='zppa_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='zppa_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
