# Generated by Django 5.1.7 on 2026-05-18 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0004_annualprocurementplan_gpn_publication_proofs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractprocurementplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract Procurement Plan', 'verbose_name_plural': 'Contract Procurement Plans'},
        ),
        migrations.AlterModelOptions(
            name='procurementmilestone',
            options={'ordering': ['sequence_number'], 'verbose_name': 'Procurement Milestone', 'verbose_name_plural': 'Procurement Milestones'},
        ),
        migrations.RemoveField(
            model_name='contractprocurementplan',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='contractprocurementplan',
            name='resource_requirements',
        ),
        migrations.RemoveField(
            model_name='contractprocurementplan',
            name='risk_assessment',
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='amendment_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpp_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='baseline_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='baseline_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpp_baseline_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='cpp_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='is_baseline_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='method',
            field=models.CharField(blank=True, choices=[('open_tender', 'Open National Bidding (ONB)'), ('international', 'International Bidding (INT)'), ('limited', 'Limited Bidding (LIM)'), ('simplified', 'Simplified Bidding (SIM)'), ('direct', 'Direct Bidding / Direct Procurement')], max_length=50),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='method_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='overall_risk_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='override_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='override_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpp_overrides_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='previous_baseline',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='recommended_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpp_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='zpc_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='zpc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='zpc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpp_zpc_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='zpc_grounds',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='zpc_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='zpc_resolution_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='procurementmilestone',
            name='is_system_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procurementmilestone',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procurementmilestone',
            name='variance_flag',
            field=models.CharField(blank=True, choices=[('green', 'On Time / Early'), ('yellow', '1-5 Days Late'), ('orange', '6-14 Days Late'), ('red', '>14 Days Late / At Risk')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractprocurementplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpp_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractprocurementplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_zpc', 'Pending ZPC Approval'), ('approved', 'Approved'), ('rejected', 'Returned for Revision'), ('active', 'Active (Procurement In Progress)'), ('amended', 'Amended'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='CPPRisk',
            fields=[
                ('risk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_category', models.CharField(choices=[('supply', 'Supply Risk'), ('price', 'Price Risk'), ('quality', 'Quality Risk'), ('delivery', 'Delivery Risk'), ('regulatory', 'Regulatory Risk'), ('capacity', 'Capacity Risk'), ('custom', 'Custom')], max_length=50)),
                ('risk_description', models.TextField()),
                ('likelihood', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('mitigation_strategy', models.TextField()),
                ('risk_owner', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='procurement_planning.contractprocurementplan')),
            ],
            options={
                'verbose_name': 'CPP Risk',
                'verbose_name_plural': 'CPP Risks',
                'db_table': 'proc_cpp_risk',
            },
        ),
    ]
