# Generated by Django 5.1.7 on 2026-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0005_alter_contractprocurementplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocurementplan',
            name='approval_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='resource_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
