# Generated by Django 5.1.7 on 2026-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0006_contractprocurementplan_approval_trail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocurementplan',
            name='is_multi_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='multi_year_commitments',
            field=models.JSONField(blank=True, default=list, help_text='Future year budget commitments: [{"fiscal_year": "2026", "amount": 500000, "funding_source": "GOZ"}]'),
        ),
    ]
