# Generated by Django 5.1.7 on 2026-05-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0007_add_multi_year_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocurementplan',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractprocurementplan',
            name='retention_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractprocurementplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_zpc', 'Pending ZPC Approval'), ('approved', 'Approved'), ('rejected', 'Returned for Revision'), ('active', 'Active (Procurement In Progress)'), ('amended', 'Amended'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
