# Generated by Django 5.1.7 on 2026-05-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0008_add_cpp_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='applineitem',
            name='is_citizen_reserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applineitem',
            name='procurement_type',
            field=models.CharField(choices=[('goods', 'Goods'), ('works', 'Works'), ('services', 'Services')], default='goods', max_length=50),
        ),
    ]
