# Generated by Django 5.1.7 on 2026-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0009_add_procurement_type_and_citizen_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='email_notification_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='email_notification_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='email_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='email_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='gazette_file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='gazette_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='gazette_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='publication_proofs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
