# Generated by Django 5.0.6 on 2026-06-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0010_add_gpn_publication_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementmilestone',
            name='variance_flag',
            field=models.CharField(blank=True, choices=[('green', 'On Time / Early'), ('yellow', '1-7 Days Late'), ('orange', '8-14 Days Late'), ('red', '>14 Days Late / Critical')], default='', max_length=20),
        ),
    ]
