# Generated by Django 5.0.6 on 2026-06-11 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0011_alter_procurementmilestone_variance_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPPDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='cpp_documents/')),
                ('document_type', models.CharField(choices=[('strategy', 'Strategy Paper'), ('market_research', 'Market Research'), ('price_quote', 'Price Quote'), ('evaluation', 'Evaluation Methodology'), ('specification', 'Specification'), ('other', 'Other Supporting Document')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement_planning.contractprocurementplan')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPP Document',
                'verbose_name_plural': 'CPP Documents',
                'db_table': 'proc_cpp_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
