# Generated by Django 5.1.7 on 2026-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0012_cppdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualprocurementplan',
            name='app_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='generalprocurementnotice',
            name='gpn_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
