# Generated by Django 5.0.6 on 2026-06-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0013_traceable_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualprocurementplan',
            name='amends',
            field=models.ForeignKey(blank=True, help_text='The original APP that this version amends', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='procurement_planning.annualprocurementplan'),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='change_justification',
            field=models.TextField(blank=True, default='', help_text='Justification for changes made in this quarterly update'),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='previous_total_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated value of the previous version, used for 20% cap enforcement', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='annualprocurementplan',
            name='version',
            field=models.IntegerField(default=1, help_text='APP version number for quarterly updates'),
        ),
    ]
