# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_created_by(apps, schema_editor):
    AnnualProcurementPlan = apps.get_model('procurement_planning', 'AnnualProcurementPlan')
    AnnualProcurementPlan.objects.filter(
        created_by__isnull=True,
        submitted_by__isnull=False,
    ).update(created_by=models.F('submitted_by'))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement_planning', '0014_add_app_quarterly_update_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualprocurementplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_created_by, migrations.RunPython.noop),
    ]
