# Generated by Django 5.0.6 on 2026-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_vendor_application_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
