# Generated by Django 5.0.6 on 2026-06-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='annual_turnover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='employee_count',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='year_established',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
