# Generated by Django 5.0.6 on 2026-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_vendorapplication_annual_turnover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='ceec_category',
            field=models.CharField(choices=[('youth', 'Youth-Owned'), ('woman', 'Woman-Owned'), ('disabled', 'PWD-Owned'), ('general', 'General Citizen Owned'), ('citizen_influenced', 'Citizen-Influenced'), ('citizen_empowered', 'Citizen-Empowered'), ('citizen_owned', 'Citizen-Owned'), ('non_citizen', 'Non-Citizen')], default='non_citizen', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='ceec_category',
            field=models.CharField(choices=[('youth', 'Youth-Owned'), ('woman', 'Woman-Owned'), ('disabled', 'PWD-Owned'), ('general', 'General Citizen Owned'), ('citizen_influenced', 'Citizen-Influenced'), ('citizen_empowered', 'Citizen-Empowered'), ('citizen_owned', 'Citizen-Owned'), ('non_citizen', 'Non-Citizen')], max_length=50),
        ),
    ]
