# Generated by Django 5.0.6 on 2026-06-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_ceec_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='commodity_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
