# Generated by Django 5.1.7 on 2026-05-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0005_alter_solicitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='egp_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='publication_proofs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='publication_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_solicitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='is_zppa_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='mandatory_clauses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
