# Generated by Django 5.0.6 on 2026-05-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0006_solicitation_egp_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='bid_security_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='bid_security_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='bid_security_type',
            field=models.CharField(blank=True, default='bank_guarantee', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='bid_validity_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='citizen_preference',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='document_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='document_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='minimum_technical_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='pre_bid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='pre_bid_venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='submission_format',
            field=models.CharField(choices=[('single', 'Single Envelope'), ('two', 'Two Envelope')], default='single', max_length=10),
        ),
    ]
