# Generated by Django 5.1.7 on 2026-06-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_planning', '0011_alter_procurementmilestone_variance_flag'),
        ('solicitations', '0007_add_solicitation_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='cpp',
            field=models.ForeignKey(blank=True, help_text='The approved CPP under which this solicitation is created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitations', to='procurement_planning.contractprocurementplan'),
        ),
    ]
