# Generated by Django 5.0.6 on 2026-06-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0008_solicitation_cpp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='clarification_cutoff',
            field=models.DateTimeField(blank=True, help_text='Deadline for suppliers to submit clarification requests (≥5 working days before closing)', null=True),
        ),
    ]
