# Generated by Django 5.0.6 on 2026-06-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0009_solicitation_clarification_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded solicitation document file', null=True, upload_to='solicitation_documents/'),
        ),
        migrations.AlterField(
            model_name='solicitationdocument',
            name='file_path',
            field=models.CharField(blank=True, default='', help_text='Legacy path/name reference', max_length=500),
        ),
    ]
