# Generated by Django 5.0.6 on 2026-06-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0010_solicitationdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriterion',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Maximum possible score for this criterion (default: 100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='scoring_guidance',
            field=models.TextField(blank=True, default='', help_text='Detailed guidance shown to evaluators during scoring'),
        ),
    ]
