# Generated by Django 5.1.7 on 2026-06-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0012_add_evaluation_method_financial_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationaddendum',
            name='original_text',
            field=models.TextField(blank=True, default='', help_text='The original text being amended (section reference)'),
        ),
        migrations.AddField(
            model_name='solicitationaddendum',
            name='revised_text',
            field=models.TextField(blank=True, default='', help_text='The revised/replacement text'),
        ),
    ]
