# Generated by Django 5.0.6 on 2026-06-25 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0013_addendum_original_revised_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationaddendum',
            name='addendum_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=30),
        ),
        migrations.AddField(
            model_name='solicitationaddendum',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitationaddendum',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_addenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitationaddendum',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
