# Generated by Django 5.0.6 on 2026-06-30 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0014_add_addendum_approval_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitationtemplate',
            options={'ordering': ['template_name', 'version'], 'verbose_name': 'Solicitation Template', 'verbose_name_plural': 'Solicitation Templates'},
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='applicable_value_range',
            field=models.JSONField(blank=True, default=dict, help_text='Min/max value range where this template applies: {"min": 0, "max": 1000000}'),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='auto_populate_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of fields to auto-populate from CPP: ["method", "estimated_value", "procurement_strategy"]'),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='procurement_type',
            field=models.CharField(choices=[('goods', 'Goods'), ('works', 'Works'), ('consulting', 'Consulting Services'), ('non_consulting', 'Non-Consulting Services')], default='goods', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='requires_cpp',
            field=models.BooleanField(default=True, help_text='Whether this template requires an approved CPP'),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='template_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='template_type',
            field=models.CharField(choices=[('itb', 'Invitation to Bid (ITB)'), ('rfp', 'Request for Proposal (RFP)'), ('rfq', 'Request for Quotation (RFQ)')], default='itb', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solicitationtemplate',
            name='document_type',
            field=models.CharField(default='bidding_document', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitationtemplate',
            name='is_zppa_template',
            field=models.BooleanField(default=True, help_text='Indicates if this is a standard ZPPA-approved template'),
        ),
        migrations.AlterField(
            model_name='solicitationtemplate',
            name='mandatory_clauses',
            field=models.JSONField(blank=True, default=list, help_text='[{"clause_id": "GC.1", "clause_text": "...", "is_locked": true}] (FR-SOL-02)'),
        ),
        migrations.AlterField(
            model_name='solicitationtemplate',
            name='method',
            field=models.CharField(blank=True, help_text='Specific procurement method (e.g. open_tender)', max_length=50),
        ),
    ]
